export const CURATED_EXISTING_KEEP_NORMALIZED_NAMES = [
  "alfredo sauce", "apple cider vinegar", "balsamic vinegar", "barbecue sauce", "buffalo sauce",
  "fish sauce", "hot sauce", "ketchup", "marinara sauce", "oyster sauce", "pesto",
  "rice vinegar", "salsa", "soy sauce", "sriracha", "taco sauce", "teriyaki sauce",
  "worcestershire sauce", "yellow mustard", "ranch dressing", "black pepper", "chili powder",
  "ground cumin", "fruit jam", "hummus", "mayonnaise", "honey", "maple syrup",
  "butter", "ghee", "half and half", "heavy cream", "sour cream", "cheddar cheese",
  "cream cheese", "feta cheese", "goat cheese", "mozzarella cheese", "parmesan cheese",
  "provolone cheese", "ricotta cheese", "string cheese", "swiss cheese", "egg",
  "egg whites", "2 milk", "buttermilk", "evaporated milk", "skim milk", "whole milk",
  "greek yogurt", "plain yogurt", "coffee", "green tea", "iced coffee", "tea",
  "apple juice", "orange juice", "oat milk", "soy milk", "unsweetened almond milk",
  "sparkling water", "water", "cottage cheese", "tofu", "frozen berries", "frozen mango",
  "frozen broccoli", "frozen corn", "frozen mixed vegetables", "frozen peas", "frozen spinach",
  "beef brisket", "beef short ribs", "beef sirloin", "ground beef", "lean ground beef",
  "chicken breast", "chicken drumstick", "chicken thigh", "chicken wing", "ground chicken",
  "canned salmon", "cod", "salmon", "sardines", "tilapia", "trout", "tuna steak",
  "bacon", "ham", "pork chop", "pork sausage", "pork shoulder", "pork tenderloin",
  "crab", "shrimp", "ground turkey", "turkey breast", "turkey slices", "baking powder",
  "baking soda", "cocoa powder", "cornstarch", "flour", "sugar", "whole wheat flour",
  "black beans", "cannellini beans", "chickpeas", "kidney beans", "lentils", "lima beans",
  "navy beans", "pinto beans", "split peas", "bagel", "corn tortilla", "english muffin",
  "flour tortilla", "hamburger bun", "hot dog bun", "naan", "pita bread", "rye bread",
  "sourdough bread", "wheat bread", "white bread", "canned chicken", "canned chickpeas",
  "canned corn", "canned kidney beans", "canned pumpkin", "canned tomatoes", "canned tuna",
  "chicken broth", "coconut milk", "tomato paste", "tomato sauce", "almond butter",
  "peanut butter", "sunflower seed butter", "tahini", "avocado oil", "canola oil",
  "coconut oil", "olive oil", "sesame oil", "vegetable oil", "egg noodles", "fettuccine",
  "macaroni", "penne pasta", "rice noodles", "spaghetti", "barley", "basmati rice",
  "brown rice", "cornmeal", "couscous", "grits", "jasmine rice", "oats", "quinoa",
  "white rice", "wild rice", "apple", "apricot", "avocado", "banana", "blackberries",
  "blueberries", "cantaloupe", "cherries", "cranberries", "dates", "grapefruit",
  "grapes", "honeydew melon", "kiwi", "lemon", "lime", "mango", "nectarine",
  "orange", "peach", "pear", "pineapple", "plum", "raspberries", "strawberries",
  "tangerine", "watermelon", "basil", "chives", "cilantro", "dill", "fresh oregano",
  "mint", "parsley", "rosemary", "sage", "thyme", "arugula", "asparagus", "beets",
  "bok choy", "broccoli", "brussels sprouts", "butternut squash", "carrots",
  "cauliflower", "celery", "collard greens", "corn", "cucumber", "eggplant", "garlic",
  "ginger root", "green beans", "green cabbage", "green onions", "green peas",
  "iceberg lettuce", "jalapeno pepper", "kale", "mixed greens", "mushrooms",
  "poblano pepper", "radishes", "red bell pepper", "red cabbage", "red onion",
  "romaine lettuce", "russet potato", "shallot", "spinach", "sweet potato",
  "swiss chard", "tomato", "yellow onion", "yellow squash", "yukon gold potato",
  "zucchini", "cashews", "chia seeds", "peanuts", "pistachios", "pumpkin seeds",
  "walnuts",
] as const;

export const CURATED_EXISTING_REMOVE_NORMALIZED_NAMES = [
  "guacamole", "hard boiled egg", "scrambled eggs", "chocolate milk", "kefir",
  "regular yogurt", "skyr", "vanilla yogurt", "kombucha", "sweet tea", "lemonade",
  "fruit smoothie", "protein shake", "diet soda", "soda", "energy drink", "sports drink",
  "coconut water", "cereal", "toast", "potatoes", "frozen salmon fillet", "frozen shrimp",
  "frozen french fries", "beef roast", "steak", "chicken nuggets", "chicken sausage",
  "rotisserie chicken", "anchovies", "haddock", "tuna", "canadian bacon", "clams",
  "mussels", "oysters", "scallops", "turkey bacon", "turkey meatballs", "turkey sausage",
  "tortilla", "canned soup", "pasta", "ramen noodles", "soba noodles", "udon noodles",
  "bulgur", "farro", "millet", "rice bowl", "breakfast burrito", "chicken alfredo",
  "chicken noodle soup", "chili", "frozen pizza", "grilled cheese", "grilled chicken salad",
  "instant ramen", "lasagna", "lentil soup", "mac and cheese", "mashed potatoes",
  "peanut butter and jelly sandwich", "spaghetti with meat sauce", "tuna sandwich",
  "vegetable soup", "burrito", "cheeseburger", "chicken sandwich", "fried rice",
  "hot dog", "quesadilla", "tacos", "figs", "pomegranate arils", "tarragon",
  "bell pepper", "onion", "granola bar", "protein bar", "potato chips", "crackers",
  "pretzels", "rice cakes", "trail mix", "dark chocolate",
] as const;

export const CURATED_ADD_NOW_NORMALIZED_NAMES = [
  "green bell pepper", "yellow bell pepper", "white onion", "leek", "red potato",
  "pumpkin", "acorn squash", "spaghetti squash", "fennel", "artichoke", "okra",
  "whole chicken", "chicken tenderloins", "chuck roast", "flank steak", "ground pork",
  "pork ribs", "catfish", "pollock", "mahi mahi", "egg yolk", "monterey jack cheese",
  "colby jack cheese", "blue cheese", "whole wheat pasta", "lasagna noodles", "orzo",
  "whole wheat tortilla", "black eyed peas", "edamame", "canned black beans",
  "canned pinto beans", "canned green beans", "canned peas", "vegetable broth",
  "beef broth", "peanut oil", "shortening", "lard", "brown sugar", "powdered sugar",
  "vanilla extract", "active dry yeast", "bread flour", "chocolate chips", "breadcrumbs",
  "frozen green beans", "frozen cauliflower", "frozen edamame", "dijon mustard",
  "white vinegar", "red wine vinegar", "pickles", "pickle relish", "salt",
  "garlic powder", "onion powder", "paprika", "smoked paprika", "cinnamon",
  "dried oregano", "dried basil", "italian seasoning", "red pepper flakes", "bay leaves",
  "curry powder", "turmeric", "ground ginger", "nutmeg", "almonds", "pecans",
  "sunflower seeds", "sesame seeds", "ground flaxseed", "raisins",
] as const;

export const CURATED_OPTIONAL_LATER_NORMALIZED_NAMES = [
  "dry white rice", "dry brown rice", "dry pasta", "dry black beans", "dry pinto beans",
  "dry chickpeas", "red lentils", "green lentils", "frozen chicken breast", "beef stew meat",
] as const;

export const CURATED_RENAMED_EXISTING_NORMALIZED_NAMES = {
  "2 milk": "2 percent milk",
} as const;
