import type { TourStep } from "@/components/tour/TourProvider";

export const dayTypesTourSteps: TourStep[] = [
  {
    id: "day-types-name",
    selector: '[data-tour="day-type-name"]',
    title: "Name the day type",
    body: "This reusable daily template is what the scheduler depends on.",
    requiresClick: false,
    allowNext: true,
    blockOutsideClicks: false,
  },
  {
    id: "day-types-coverage",
    selector: '[data-tour="day-type-coverage"]',
    title: "Cover 24 hours",
    body: "Your Day Type must cover the full 24 hours (00:00–24:00); this status tells you what’s missing so you can fill to 24h.",
    requiresClick: false,
    allowNext: true,
    blockOutsideClicks: false,
  },
  {
    id: "day-types-add-block",
    selector: '[data-tour="day-type-add-block"]',
    title: "Add a time block",
    body: "Time blocks define what can happen when; stack them until coverage is full.",
    requiresClick: false,
    allowNext: true,
    blockOutsideClicks: false,
  },
  {
    id: "day-types-block-start",
    selector: '[data-tour="day-type-block-start"]',
    title: "Pick a start time",
    body: "Choose a start that fills the next gap so each block helps fill to 24h.",
    requiresClick: false,
    allowNext: true,
    blockOutsideClicks: false,
  },
  {
    id: "day-types-block-end",
    selector: '[data-tour="day-type-block-end"]',
    title: "Pick an end time",
    body: "End the block where it should stop so the next one can keep filling toward 24h.",
    requiresClick: false,
    allowNext: true,
    blockOutsideClicks: false,
  },
  {
    id: "day-types-constraints",
    selector: '[data-tour="day-type-constraints"]',
    title: "Add constraints (optional)",
    body: "Constraints (location, monument, etc.) narrow when a block applies; you can skip them for now.",
    requiresClick: false,
    allowNext: true,
    blockOutsideClicks: false,
  },
  {
    id: "day-types-save",
    selector: '[data-tour="day-type-save"]',
    title: "Save and unlock scheduling",
    body: "Save to make this template usable on the schedule and safely leave the page when you’re done.",
    requiresClick: false,
    allowNext: true,
    blockOutsideClicks: false,
  },
];
