-- Expand the shared generic Nutrition foods catalog with common grocery foods.

BEGIN;

WITH seed_foods(
  canonical_key, name, normalized_name, food_family, icon_name, search_aliases,
  serving_size, serving_unit, serving_grams, calories, carbs_g, protein_g, fat_g,
  browse_placements
) AS (
  VALUES
    ('pear', 'Pear', 'pear', 'Fruit', 'pear', ARRAY['fresh pear'], 100, 'g', 100, 57, 15.2, 0.4, 0.1, ARRAY['Produce|Fruit', 'Everyday|Quick snacks']),
    ('peach', 'Peach', 'peach', 'Fruit', 'peach', ARRAY['fresh peach'], 100, 'g', 100, 39, 9.5, 0.9, 0.3, ARRAY['Produce|Fruit']),
    ('nectarine', 'Nectarine', 'nectarine', 'Fruit', 'peach', ARRAY['fresh nectarine'], 100, 'g', 100, 44, 10.6, 1.1, 0.3, ARRAY['Produce|Fruit']),
    ('plum', 'Plum', 'plum', 'Fruit', 'plum', ARRAY['fresh plum'], 100, 'g', 100, 46, 11.4, 0.7, 0.3, ARRAY['Produce|Fruit']),
    ('apricot', 'Apricot', 'apricot', 'Fruit', 'apricot', ARRAY['fresh apricot'], 100, 'g', 100, 48, 11.1, 1.4, 0.4, ARRAY['Produce|Fruit']),
    ('mango', 'Mango', 'mango', 'Fruit', 'mango', ARRAY['fresh mango'], 100, 'g', 100, 60, 15, 0.8, 0.4, ARRAY['Produce|Fruit']),
    ('pineapple', 'Pineapple', 'pineapple', 'Fruit', 'pineapple', ARRAY['fresh pineapple'], 100, 'g', 100, 50, 13.1, 0.5, 0.1, ARRAY['Produce|Fruit']),
    ('kiwi', 'Kiwi', 'kiwi', 'Fruit', 'kiwi', ARRAY['kiwifruit'], 100, 'g', 100, 61, 14.7, 1.1, 0.5, ARRAY['Produce|Fruit']),
    ('watermelon', 'Watermelon', 'watermelon', 'Fruit', 'watermelon', ARRAY['fresh watermelon'], 100, 'g', 100, 30, 7.6, 0.6, 0.2, ARRAY['Produce|Fruit']),
    ('cantaloupe', 'Cantaloupe', 'cantaloupe', 'Fruit', 'melon', ARRAY['fresh cantaloupe'], 100, 'g', 100, 34, 8.2, 0.8, 0.2, ARRAY['Produce|Fruit']),
    ('honeydew-melon', 'Honeydew melon', 'honeydew melon', 'Fruit', 'melon', ARRAY['fresh honeydew'], 100, 'g', 100, 36, 9.1, 0.5, 0.1, ARRAY['Produce|Fruit']),
    ('raspberries', 'Raspberries', 'raspberries', 'Berries', 'raspberry', ARRAY['fresh raspberries'], 1, 'cup', 123, 64, 14.7, 1.5, 0.8, ARRAY['Produce|Fruit', 'Everyday|Quick snacks']),
    ('blackberries', 'Blackberries', 'blackberries', 'Berries', 'blackberry', ARRAY['fresh blackberries'], 1, 'cup', 144, 62, 13.8, 2, 0.7, ARRAY['Produce|Fruit', 'Everyday|Quick snacks']),
    ('cherries', 'Cherries', 'cherries', 'Fruit', 'cherry', ARRAY['fresh cherries'], 1, 'cup', 154, 97, 24.7, 1.6, 0.3, ARRAY['Produce|Fruit']),
    ('pomegranate-arils', 'Pomegranate arils', 'pomegranate arils', 'Fruit', 'pomegranate', ARRAY['pomegranate seeds'], 0.5, 'cup', 87, 72, 16.3, 1.5, 1, ARRAY['Produce|Fruit']),
    ('grapefruit', 'Grapefruit', 'grapefruit', 'Citrus', 'grapefruit', ARRAY['fresh grapefruit'], 100, 'g', 100, 42, 10.7, 0.8, 0.1, ARRAY['Produce|Fruit']),
    ('lemon', 'Lemon', 'lemon', 'Citrus', 'lemon', ARRAY['fresh lemon'], 100, 'g', 100, 29, 9.3, 1.1, 0.3, ARRAY['Produce|Fruit', 'Produce|Herbs']),
    ('lime', 'Lime', 'lime', 'Citrus', 'lime', ARRAY['fresh lime'], 100, 'g', 100, 30, 10.5, 0.7, 0.2, ARRAY['Produce|Fruit', 'Produce|Herbs']),
    ('tangerine', 'Tangerine', 'tangerine', 'Citrus', 'orange', ARRAY['mandarin orange'], 100, 'g', 100, 53, 13.3, 0.8, 0.3, ARRAY['Produce|Fruit']),
    ('dates', 'Dates', 'dates', 'Dried Fruit', 'date', ARRAY['dried dates'], 2, 'pieces', 48, 133, 36, 0.9, 0.2, ARRAY['Produce|Fruit', 'Snacks|Sweet snacks']),
    ('figs', 'Figs', 'figs', 'Fruit', 'fig', ARRAY['fresh figs'], 100, 'g', 100, 74, 19.2, 0.8, 0.3, ARRAY['Produce|Fruit']),
    ('cranberries', 'Cranberries', 'cranberries', 'Berries', 'cranberry', ARRAY['fresh cranberries'], 1, 'cup', 100, 46, 12.2, 0.4, 0.1, ARRAY['Produce|Fruit']),
    ('cucumber', 'Cucumber', 'cucumber', 'Vegetable', 'cucumber', ARRAY['fresh cucumber'], 100, 'g', 100, 15, 3.6, 0.7, 0.1, ARRAY['Produce|Vegetables']),
    ('zucchini', 'Zucchini', 'zucchini', 'Vegetable', 'zucchini', ARRAY['courgette'], 100, 'g', 100, 17, 3.1, 1.2, 0.3, ARRAY['Produce|Vegetables']),
    ('yellow-squash', 'Yellow squash', 'yellow squash', 'Vegetable', 'squash', ARRAY['summer squash'], 100, 'g', 100, 16, 3.4, 1.2, 0.2, ARRAY['Produce|Vegetables']),
    ('eggplant', 'Eggplant', 'eggplant', 'Vegetable', 'eggplant', ARRAY['aubergine'], 100, 'g', 100, 25, 5.9, 1, 0.2, ARRAY['Produce|Vegetables']),
    ('cauliflower', 'Cauliflower', 'cauliflower', 'Vegetable', 'cauliflower', ARRAY['fresh cauliflower'], 100, 'g', 100, 25, 5, 1.9, 0.3, ARRAY['Produce|Vegetables']),
    ('brussels-sprouts', 'Brussels sprouts', 'brussels sprouts', 'Vegetable', 'brussels sprouts', ARRAY['fresh brussels sprouts'], 100, 'g', 100, 43, 9, 3.4, 0.3, ARRAY['Produce|Vegetables']),
    ('asparagus', 'Asparagus', 'asparagus', 'Vegetable', 'asparagus', ARRAY['fresh asparagus'], 100, 'g', 100, 20, 3.9, 2.2, 0.1, ARRAY['Produce|Vegetables']),
    ('green-beans', 'Green beans', 'green beans', 'Vegetable', 'green beans', ARRAY['string beans'], 100, 'g', 100, 31, 7, 1.8, 0.1, ARRAY['Produce|Vegetables']),
    ('green-peas', 'Green peas', 'green peas', 'Vegetable', 'peas', ARRAY['peas'], 0.5, 'cup', 80, 67, 12, 4.3, 0.3, ARRAY['Produce|Vegetables', 'Everyday|Cheap bulk foods']),
    ('celery', 'Celery', 'celery', 'Vegetable', 'celery', ARRAY['fresh celery'], 100, 'g', 100, 14, 3, 0.7, 0.2, ARRAY['Produce|Vegetables']),
    ('green-cabbage', 'Green cabbage', 'green cabbage', 'Vegetable', 'cabbage', ARRAY['cabbage'], 100, 'g', 100, 25, 5.8, 1.3, 0.1, ARRAY['Produce|Vegetables', 'Everyday|Cheap bulk foods']),
    ('red-cabbage', 'Red cabbage', 'red cabbage', 'Vegetable', 'cabbage', ARRAY['purple cabbage'], 100, 'g', 100, 31, 7.4, 1.4, 0.2, ARRAY['Produce|Vegetables']),
    ('kale', 'Kale', 'kale', 'Leafy Greens', 'kale', ARRAY['fresh kale'], 100, 'g', 100, 49, 8.8, 4.3, 0.9, ARRAY['Produce|Vegetables']),
    ('arugula', 'Arugula', 'arugula', 'Leafy Greens', 'greens', ARRAY['rocket greens'], 100, 'g', 100, 25, 3.7, 2.6, 0.7, ARRAY['Produce|Vegetables']),
    ('collard-greens', 'Collard greens', 'collard greens', 'Leafy Greens', 'greens', ARRAY['fresh collards'], 100, 'g', 100, 32, 5.4, 3, 0.6, ARRAY['Produce|Vegetables']),
    ('swiss-chard', 'Swiss chard', 'swiss chard', 'Leafy Greens', 'greens', ARRAY['chard'], 100, 'g', 100, 19, 3.7, 1.8, 0.2, ARRAY['Produce|Vegetables']),
    ('bok-choy', 'Bok choy', 'bok choy', 'Vegetable', 'bok choy', ARRAY['pak choi'], 100, 'g', 100, 13, 2.2, 1.5, 0.2, ARRAY['Produce|Vegetables']),
    ('iceberg-lettuce', 'Iceberg lettuce', 'iceberg lettuce', 'Leafy Greens', 'lettuce', ARRAY['head lettuce'], 100, 'g', 100, 14, 3, 0.9, 0.1, ARRAY['Produce|Vegetables']),
    ('mixed-greens', 'Mixed greens', 'mixed greens', 'Leafy Greens', 'greens', ARRAY['spring mix', 'salad greens'], 2, 'cups', 85, 20, 3.5, 1.8, 0.3, ARRAY['Produce|Vegetables']),
    ('red-bell-pepper', 'Red bell pepper', 'red bell pepper', 'Pepper', 'pepper', ARRAY['sweet red pepper'], 100, 'g', 100, 31, 6, 1, 0.3, ARRAY['Produce|Vegetables']),
    ('jalapeno-pepper', 'Jalapeno pepper', 'jalapeno pepper', 'Pepper', 'pepper', ARRAY['jalapeno chile'], 1, 'pepper', 14, 4, 0.9, 0.1, 0.1, ARRAY['Produce|Vegetables', 'Produce|Herbs']),
    ('poblano-pepper', 'Poblano pepper', 'poblano pepper', 'Pepper', 'pepper', ARRAY['poblano chile'], 100, 'g', 100, 20, 4.6, 0.9, 0.2, ARRAY['Produce|Vegetables']),
    ('yellow-onion', 'Yellow onion', 'yellow onion', 'Aromatic', 'onion', ARRAY['cooking onion'], 100, 'g', 100, 40, 9.3, 1.1, 0.1, ARRAY['Produce|Vegetables']),
    ('red-onion', 'Red onion', 'red onion', 'Aromatic', 'onion', ARRAY['purple onion'], 100, 'g', 100, 40, 9.3, 1.1, 0.1, ARRAY['Produce|Vegetables']),
    ('green-onions', 'Green onions', 'green onions', 'Aromatic', 'onion', ARRAY['scallions'], 100, 'g', 100, 32, 7.3, 1.8, 0.2, ARRAY['Produce|Vegetables', 'Produce|Herbs']),
    ('shallot', 'Shallot', 'shallot', 'Aromatic', 'onion', ARRAY['fresh shallot'], 100, 'g', 100, 72, 16.8, 2.5, 0.1, ARRAY['Produce|Vegetables']),
    ('garlic', 'Garlic', 'garlic', 'Aromatic', 'garlic', ARRAY['fresh garlic'], 1, 'clove', 3, 4, 1, 0.2, 0, ARRAY['Produce|Vegetables', 'Produce|Herbs']),
    ('ginger-root', 'Ginger root', 'ginger root', 'Aromatic', 'ginger', ARRAY['fresh ginger'], 1, 'tbsp', 6, 5, 1.1, 0.1, 0.1, ARRAY['Produce|Vegetables', 'Produce|Herbs']),
    ('russet-potato', 'Russet potato', 'russet potato', 'Vegetable', 'potato', ARRAY['baking potato'], 1, 'medium', 213, 168, 38, 4.6, 0.2, ARRAY['Produce|Vegetables', 'Everyday|Cheap bulk foods']),
    ('yukon-gold-potato', 'Yukon gold potato', 'yukon gold potato', 'Vegetable', 'potato', ARRAY['gold potato'], 1, 'medium', 173, 161, 37, 4.3, 0.2, ARRAY['Produce|Vegetables', 'Everyday|Cheap bulk foods']),
    ('butternut-squash', 'Butternut squash', 'butternut squash', 'Vegetable', 'squash', ARRAY['winter squash'], 100, 'g', 100, 45, 11.7, 1, 0.1, ARRAY['Produce|Vegetables']),
    ('mushrooms', 'Mushrooms', 'mushrooms', 'Mushroom', 'mushroom', ARRAY['white mushrooms'], 100, 'g', 100, 22, 3.3, 3.1, 0.3, ARRAY['Produce|Vegetables']),
    ('corn', 'Corn', 'corn', 'Vegetable', 'corn', ARRAY['sweet corn'], 0.5, 'cup', 82, 72, 16, 2.5, 1, ARRAY['Produce|Vegetables', 'Everyday|Cheap bulk foods']),
    ('beets', 'Beets', 'beets', 'Vegetable', 'beet', ARRAY['red beets'], 100, 'g', 100, 43, 9.6, 1.6, 0.2, ARRAY['Produce|Vegetables']),
    ('radishes', 'Radishes', 'radishes', 'Vegetable', 'radish', ARRAY['fresh radishes'], 100, 'g', 100, 16, 3.4, 0.7, 0.1, ARRAY['Produce|Vegetables']),
    ('mint', 'Mint', 'mint', 'Herb', 'mint', ARRAY['fresh mint'], 0.25, 'cup', 6, 4, 0.8, 0.2, 0, ARRAY['Produce|Herbs']),
    ('dill', 'Dill', 'dill', 'Herb', 'dill', ARRAY['fresh dill'], 0.25, 'cup', 9, 4, 0.6, 0.3, 0.1, ARRAY['Produce|Herbs']),
    ('rosemary', 'Rosemary', 'rosemary', 'Herb', 'rosemary', ARRAY['fresh rosemary'], 1, 'tbsp', 2, 3, 0.4, 0.1, 0.1, ARRAY['Produce|Herbs']),
    ('thyme', 'Thyme', 'thyme', 'Herb', 'thyme', ARRAY['fresh thyme'], 1, 'tbsp', 2, 2, 0.4, 0.1, 0, ARRAY['Produce|Herbs']),
    ('fresh-oregano', 'Fresh oregano', 'fresh oregano', 'Herb', 'oregano', ARRAY['oregano leaves'], 1, 'tbsp', 3, 3, 0.7, 0.1, 0.1, ARRAY['Produce|Herbs']),
    ('sage', 'Sage', 'sage', 'Herb', 'sage', ARRAY['fresh sage'], 1, 'tbsp', 2, 2, 0.4, 0.1, 0.1, ARRAY['Produce|Herbs']),
    ('chives', 'Chives', 'chives', 'Herb', 'chives', ARRAY['fresh chives'], 1, 'tbsp', 3, 1, 0.1, 0.1, 0, ARRAY['Produce|Herbs']),
    ('tarragon', 'Tarragon', 'tarragon', 'Herb', 'tarragon', ARRAY['fresh tarragon'], 1, 'tbsp', 2, 1, 0.2, 0.1, 0, ARRAY['Produce|Herbs']),
    ('chicken-drumstick', 'Chicken drumstick', 'chicken drumstick', 'Chicken', 'chicken', ARRAY['chicken leg'], 100, 'g', 100, 216, 0, 27, 11, ARRAY['Meat & Seafood|Chicken', 'Everyday|High protein regulars']),
    ('chicken-wing', 'Chicken wing', 'chicken wing', 'Chicken', 'chicken', ARRAY['plain chicken wings'], 100, 'g', 100, 203, 0, 30.5, 8.1, ARRAY['Meat & Seafood|Chicken']),
    ('ground-chicken', 'Ground chicken', 'ground chicken', 'Chicken', 'chicken', ARRAY['minced chicken'], 100, 'g', 100, 143, 0, 17.4, 8.1, ARRAY['Meat & Seafood|Chicken', 'Everyday|High protein regulars']),
    ('chicken-sausage', 'Chicken sausage', 'chicken sausage', 'Chicken', 'sausage', ARRAY['poultry sausage'], 1, 'link', 85, 140, 2, 16, 7, ARRAY['Meat & Seafood|Chicken']),
    ('lean-ground-beef', 'Lean ground beef', 'lean ground beef', 'Beef', 'beef', ARRAY['90 percent ground beef'], 100, 'g', 100, 176, 0, 20, 10, ARRAY['Meat & Seafood|Beef', 'Everyday|High protein regulars']),
    ('beef-sirloin', 'Beef sirloin', 'beef sirloin', 'Beef', 'beef', ARRAY['sirloin steak'], 100, 'g', 100, 183, 0, 29, 7, ARRAY['Meat & Seafood|Beef']),
    ('beef-brisket', 'Beef brisket', 'beef brisket', 'Beef', 'beef', ARRAY['brisket'], 100, 'g', 100, 246, 0, 29, 14, ARRAY['Meat & Seafood|Beef']),
    ('beef-short-ribs', 'Beef short ribs', 'beef short ribs', 'Beef', 'beef', ARRAY['short ribs'], 100, 'g', 100, 310, 0, 20, 25, ARRAY['Meat & Seafood|Beef']),
    ('pork-tenderloin', 'Pork tenderloin', 'pork tenderloin', 'Pork', 'pork', ARRAY['lean pork tenderloin'], 100, 'g', 100, 143, 0, 26, 3.5, ARRAY['Meat & Seafood|Pork', 'Everyday|High protein regulars']),
    ('pork-shoulder', 'Pork shoulder', 'pork shoulder', 'Pork', 'pork', ARRAY['pork butt'], 100, 'g', 100, 250, 0, 25, 16, ARRAY['Meat & Seafood|Pork']),
    ('pork-sausage', 'Pork sausage', 'pork sausage', 'Pork', 'sausage', ARRAY['breakfast sausage'], 1, 'link', 45, 150, 1, 7, 13, ARRAY['Meat & Seafood|Pork']),
    ('canadian-bacon', 'Canadian bacon', 'canadian bacon', 'Pork', 'pork', ARRAY['back bacon'], 3, 'slices', 51, 60, 1, 12, 1.5, ARRAY['Meat & Seafood|Pork']),
    ('turkey-breast', 'Turkey breast', 'turkey breast', 'Turkey', 'turkey', ARRAY['roasted turkey breast'], 100, 'g', 100, 135, 0, 30, 1, ARRAY['Meat & Seafood|Turkey', 'Everyday|High protein regulars']),
    ('turkey-sausage', 'Turkey sausage', 'turkey sausage', 'Turkey', 'sausage', ARRAY['poultry sausage'], 1, 'link', 85, 147, 1, 16, 8, ARRAY['Meat & Seafood|Turkey']),
    ('turkey-meatballs', 'Turkey meatballs', 'turkey meatballs', 'Turkey', 'meatballs', ARRAY['ground turkey meatballs'], 3, 'pieces', 85, 180, 7, 18, 9, ARRAY['Meat & Seafood|Turkey', 'Frozen|Frozen protein']),
    ('cod', 'Cod', 'cod', 'Fish', 'fish', ARRAY['cod fillet'], 100, 'g', 100, 105, 0, 23, 0.9, ARRAY['Meat & Seafood|Fish', 'Everyday|High protein regulars']),
    ('haddock', 'Haddock', 'haddock', 'Fish', 'fish', ARRAY['haddock fillet'], 100, 'g', 100, 90, 0, 20, 0.6, ARRAY['Meat & Seafood|Fish']),
    ('trout', 'Trout', 'trout', 'Fish', 'fish', ARRAY['rainbow trout'], 100, 'g', 100, 190, 0, 26, 9, ARRAY['Meat & Seafood|Fish']),
    ('tuna-steak', 'Tuna steak', 'tuna steak', 'Fish', 'tuna', ARRAY['ahi tuna'], 100, 'g', 100, 132, 0, 28, 1, ARRAY['Meat & Seafood|Fish']),
    ('canned-salmon', 'Canned salmon', 'canned salmon', 'Fish', 'salmon', ARRAY['salmon can'], 3, 'oz', 85, 117, 0, 18, 4.5, ARRAY['Meat & Seafood|Fish', 'Pantry|Canned foods']),
    ('anchovies', 'Anchovies', 'anchovies', 'Fish', 'fish', ARRAY['canned anchovies'], 1, 'oz', 28, 60, 0, 8, 2.7, ARRAY['Meat & Seafood|Fish', 'Pantry|Canned foods']),
    ('mussels', 'Mussels', 'mussels', 'Seafood', 'seafood', ARRAY['blue mussels'], 100, 'g', 100, 172, 7.4, 24, 4.5, ARRAY['Meat & Seafood|Seafood']),
    ('clams', 'Clams', 'clams', 'Seafood', 'seafood', ARRAY['cooked clams'], 100, 'g', 100, 148, 5.1, 26, 2, ARRAY['Meat & Seafood|Seafood']),
    ('oysters', 'Oysters', 'oysters', 'Seafood', 'seafood', ARRAY['raw oysters'], 100, 'g', 100, 81, 4.9, 9.5, 2.3, ARRAY['Meat & Seafood|Seafood']),
    ('hard-boiled-egg', 'Hard-boiled egg', 'hard boiled egg', 'Eggs', 'egg', ARRAY['boiled egg'], 1, 'large', 50, 78, 0.6, 6.3, 5.3, ARRAY['Dairy & Eggs|Eggs', 'Everyday|Breakfast basics', 'Everyday|High protein regulars']),
    ('scrambled-eggs', 'Scrambled eggs', 'scrambled eggs', 'Eggs', 'egg', ARRAY['plain scrambled eggs'], 0.5, 'cup', 110, 166, 2.2, 11, 12, ARRAY['Dairy & Eggs|Eggs', 'Everyday|Breakfast basics']),
    ('half-and-half', 'Half and half', 'half and half', 'Cream', 'milk', ARRAY['coffee cream'], 2, 'tbsp', 30, 40, 1.3, 1, 3.4, ARRAY['Dairy & Eggs|Butter / Cream', 'Drinks|Coffee / tea']),
    ('buttermilk', 'Buttermilk', 'buttermilk', 'Milk', 'milk', ARRAY['cultured buttermilk'], 1, 'cup', 245, 98, 12, 8, 2.2, ARRAY['Dairy & Eggs|Milk', 'Pantry|Baking']),
    ('kefir', 'Kefir', 'kefir', 'Yogurt', 'milk', ARRAY['plain kefir'], 1, 'cup', 240, 110, 12, 9, 2.5, ARRAY['Dairy & Eggs|Yogurt', 'Drinks|Protein drinks']),
    ('plain-yogurt', 'Plain yogurt', 'plain yogurt', 'Yogurt', 'yogurt', ARRAY['unsweetened yogurt'], 1, 'cup', 245, 149, 11.4, 8.5, 8, ARRAY['Dairy & Eggs|Yogurt']),
    ('skyr', 'Skyr', 'skyr', 'Yogurt', 'yogurt', ARRAY['icelandic yogurt'], 0.75, 'cup', 170, 110, 8, 19, 0.5, ARRAY['Dairy & Eggs|Yogurt', 'Everyday|High protein regulars']),
    ('ricotta-cheese', 'Ricotta cheese', 'ricotta cheese', 'Cheese', 'cheese', ARRAY['ricotta'], 0.25, 'cup', 62, 108, 3.8, 7, 8, ARRAY['Dairy & Eggs|Cheese']),
    ('feta-cheese', 'Feta cheese', 'feta cheese', 'Cheese', 'cheese', ARRAY['feta'], 1, 'oz', 28, 75, 1.2, 4, 6, ARRAY['Dairy & Eggs|Cheese']),
    ('parmesan-cheese', 'Parmesan cheese', 'parmesan cheese', 'Cheese', 'cheese', ARRAY['grated parmesan'], 1, 'oz', 28, 122, 1.2, 10, 8.1, ARRAY['Dairy & Eggs|Cheese']),
    ('swiss-cheese', 'Swiss cheese', 'swiss cheese', 'Cheese', 'cheese', ARRAY['swiss'], 1, 'oz', 28, 111, 0.4, 7.6, 8.8, ARRAY['Dairy & Eggs|Cheese']),
    ('provolone-cheese', 'Provolone cheese', 'provolone cheese', 'Cheese', 'cheese', ARRAY['provolone'], 1, 'oz', 28, 98, 0.6, 7.2, 7.5, ARRAY['Dairy & Eggs|Cheese']),
    ('goat-cheese', 'Goat cheese', 'goat cheese', 'Cheese', 'cheese', ARRAY['chevre'], 1, 'oz', 28, 103, 0.6, 6, 8.4, ARRAY['Dairy & Eggs|Cheese']),
    ('evaporated-milk', 'Evaporated milk', 'evaporated milk', 'Milk', 'milk', ARRAY['canned evaporated milk'], 0.5, 'cup', 126, 170, 13.3, 8.5, 9.5, ARRAY['Dairy & Eggs|Milk', 'Pantry|Canned foods']),
    ('ghee', 'Ghee', 'ghee', 'Cooking Fat', 'butter', ARRAY['clarified butter'], 1, 'tbsp', 14, 123, 0, 0, 14, ARRAY['Dairy & Eggs|Butter / Cream', 'Pantry|Oils']),
    ('jasmine-rice', 'Jasmine rice', 'jasmine rice', 'Rice', 'rice', ARRAY['cooked jasmine rice'], 1, 'cup cooked', 158, 205, 45, 4.2, 0.4, ARRAY['Pantry|Rice & grains', 'Everyday|Cheap bulk foods']),
    ('basmati-rice', 'Basmati rice', 'basmati rice', 'Rice', 'rice', ARRAY['cooked basmati rice'], 1, 'cup cooked', 158, 205, 45, 4.2, 0.4, ARRAY['Pantry|Rice & grains', 'Everyday|Cheap bulk foods']),
    ('wild-rice', 'Wild rice', 'wild rice', 'Grain', 'rice', ARRAY['cooked wild rice'], 1, 'cup cooked', 164, 166, 35, 6.5, 0.6, ARRAY['Pantry|Rice & grains']),
    ('barley', 'Barley', 'barley', 'Grain', 'grain', ARRAY['cooked barley'], 1, 'cup cooked', 157, 193, 44, 3.5, 0.7, ARRAY['Pantry|Rice & grains']),
    ('farro', 'Farro', 'farro', 'Grain', 'grain', ARRAY['cooked farro'], 1, 'cup cooked', 170, 200, 37, 7, 1.5, ARRAY['Pantry|Rice & grains']),
    ('bulgur', 'Bulgur', 'bulgur', 'Grain', 'grain', ARRAY['cooked bulgur'], 1, 'cup cooked', 182, 151, 34, 5.6, 0.4, ARRAY['Pantry|Rice & grains']),
    ('millet', 'Millet', 'millet', 'Grain', 'grain', ARRAY['cooked millet'], 1, 'cup cooked', 174, 207, 41, 6, 1.7, ARRAY['Pantry|Rice & grains']),
    ('cornmeal', 'Cornmeal', 'cornmeal', 'Grain', 'corn', ARRAY['dry cornmeal'], 0.25, 'cup', 31, 110, 23, 2.4, 1, ARRAY['Pantry|Rice & grains', 'Pantry|Baking']),
    ('grits', 'Grits', 'grits', 'Grain', 'corn', ARRAY['cooked grits'], 1, 'cup cooked', 242, 182, 38, 4.4, 1, ARRAY['Pantry|Rice & grains', 'Everyday|Breakfast basics']),
    ('penne-pasta', 'Penne pasta', 'penne pasta', 'Pasta', 'pasta', ARRAY['cooked penne'], 1, 'cup cooked', 140, 220, 43, 8, 1.3, ARRAY['Pantry|Pasta']),
    ('fettuccine', 'Fettuccine', 'fettuccine', 'Pasta', 'pasta', ARRAY['cooked fettuccine'], 1, 'cup cooked', 140, 220, 43, 8, 1.3, ARRAY['Pantry|Pasta']),
    ('egg-noodles', 'Egg noodles', 'egg noodles', 'Noodles', 'pasta', ARRAY['cooked egg noodles'], 1, 'cup cooked', 160, 221, 40, 7.3, 3.3, ARRAY['Pantry|Pasta']),
    ('rice-noodles', 'Rice noodles', 'rice noodles', 'Noodles', 'pasta', ARRAY['cooked rice noodles'], 1, 'cup cooked', 176, 190, 42, 1.8, 0.4, ARRAY['Pantry|Pasta']),
    ('soba-noodles', 'Soba noodles', 'soba noodles', 'Noodles', 'pasta', ARRAY['cooked soba'], 1, 'cup cooked', 114, 113, 24, 5.8, 0.1, ARRAY['Pantry|Pasta']),
    ('udon-noodles', 'Udon noodles', 'udon noodles', 'Noodles', 'pasta', ARRAY['cooked udon'], 1, 'cup cooked', 160, 210, 43, 6, 1, ARRAY['Pantry|Pasta']),
    ('sourdough-bread', 'Sourdough bread', 'sourdough bread', 'Bread', 'bread', ARRAY['sourdough slice'], 1, 'slice', 38, 100, 20, 4, 0.8, ARRAY['Pantry|Bread & tortillas']),
    ('rye-bread', 'Rye bread', 'rye bread', 'Bread', 'bread', ARRAY['rye slice'], 1, 'slice', 32, 83, 15.5, 2.7, 1.1, ARRAY['Pantry|Bread & tortillas']),
    ('pita-bread', 'Pita bread', 'pita bread', 'Bread', 'bread', ARRAY['pita pocket'], 1, 'pita', 60, 165, 33, 5.5, 0.7, ARRAY['Pantry|Bread & tortillas']),
    ('naan', 'Naan', 'naan', 'Bread', 'bread', ARRAY['naan bread'], 1, 'piece', 90, 262, 45, 8.7, 5.1, ARRAY['Pantry|Bread & tortillas']),
    ('corn-tortilla', 'Corn tortilla', 'corn tortilla', 'Tortilla', 'tortilla', ARRAY['maize tortilla'], 1, 'tortilla', 24, 52, 11, 1.4, 0.7, ARRAY['Pantry|Bread & tortillas']),
    ('flour-tortilla', 'Flour tortilla', 'flour tortilla', 'Tortilla', 'tortilla', ARRAY['wheat tortilla'], 1, 'medium', 49, 140, 24, 4, 3, ARRAY['Pantry|Bread & tortillas']),
    ('hamburger-bun', 'Hamburger bun', 'hamburger bun', 'Bread', 'bread', ARRAY['burger bun'], 1, 'bun', 52, 140, 26, 4.5, 2, ARRAY['Pantry|Bread & tortillas']),
    ('hot-dog-bun', 'Hot dog bun', 'hot dog bun', 'Bread', 'bread', ARRAY['frankfurter bun'], 1, 'bun', 43, 120, 22, 4, 1.5, ARRAY['Pantry|Bread & tortillas']),
    ('kidney-beans', 'Kidney beans', 'kidney beans', 'Beans', 'beans', ARRAY['red kidney beans'], 0.5, 'cup cooked', 88, 112, 20, 7.7, 0.4, ARRAY['Pantry|Beans & legumes', 'Everyday|Cheap bulk foods']),
    ('navy-beans', 'Navy beans', 'navy beans', 'Beans', 'beans', ARRAY['white beans'], 0.5, 'cup cooked', 91, 127, 24, 7.5, 0.5, ARRAY['Pantry|Beans & legumes', 'Everyday|Cheap bulk foods']),
    ('cannellini-beans', 'Cannellini beans', 'cannellini beans', 'Beans', 'beans', ARRAY['white kidney beans'], 0.5, 'cup cooked', 90, 110, 20, 8, 0.5, ARRAY['Pantry|Beans & legumes']),
    ('lima-beans', 'Lima beans', 'lima beans', 'Beans', 'beans', ARRAY['butter beans'], 0.5, 'cup cooked', 85, 108, 20, 7.3, 0.3, ARRAY['Pantry|Beans & legumes']),
    ('split-peas', 'Split peas', 'split peas', 'Legume', 'peas', ARRAY['dry split peas cooked'], 0.5, 'cup cooked', 98, 116, 21, 8.2, 0.4, ARRAY['Pantry|Beans & legumes']),
    ('tahini', 'Tahini', 'tahini', 'Seed Butter', 'seeds', ARRAY['sesame paste'], 1, 'tbsp', 15, 89, 3.2, 2.6, 8, ARRAY['Pantry|Nut butters', 'Condiments & Sauces|Spreads']),
    ('sunflower-seed-butter', 'Sunflower seed butter', 'sunflower seed butter', 'Seed Butter', 'seeds', ARRAY['sunbutter'], 2, 'tbsp', 32, 200, 7, 7, 18, ARRAY['Pantry|Nut butters']),
    ('canola-oil', 'Canola oil', 'canola oil', 'Oil', 'oil', ARRAY['rapeseed oil'], 1, 'tbsp', 14, 124, 0, 0, 14, ARRAY['Pantry|Oils']),
    ('avocado-oil', 'Avocado oil', 'avocado oil', 'Oil', 'oil', ARRAY['cooking avocado oil'], 1, 'tbsp', 14, 124, 0, 0, 14, ARRAY['Pantry|Oils']),
    ('sesame-oil', 'Sesame oil', 'sesame oil', 'Oil', 'oil', ARRAY['toasted sesame oil'], 1, 'tbsp', 14, 120, 0, 0, 14, ARRAY['Pantry|Oils', 'Condiments & Sauces|Sauces']),
    ('whole-wheat-flour', 'Whole wheat flour', 'whole wheat flour', 'Baking Ingredient', 'flour', ARRAY['wholemeal flour'], 0.25, 'cup', 30, 102, 22, 4, 0.6, ARRAY['Pantry|Baking']),
    ('baking-powder', 'Baking powder', 'baking powder', 'Baking Ingredient', 'baking', ARRAY['leavening powder'], 1, 'tsp', 4.6, 2, 1.3, 0, 0, ARRAY['Pantry|Baking']),
    ('canned-kidney-beans', 'Canned kidney beans', 'canned kidney beans', 'Canned Beans', 'beans', ARRAY['kidney beans can'], 0.5, 'cup', 130, 110, 20, 7, 0.5, ARRAY['Pantry|Canned foods', 'Pantry|Beans & legumes']),
    ('canned-chickpeas', 'Canned chickpeas', 'canned chickpeas', 'Canned Beans', 'beans', ARRAY['garbanzo beans can'], 0.5, 'cup', 130, 120, 21, 6, 2, ARRAY['Pantry|Canned foods', 'Pantry|Beans & legumes']),
    ('canned-pumpkin', 'Canned pumpkin', 'canned pumpkin', 'Canned Vegetable', 'pumpkin', ARRAY['pumpkin puree'], 0.5, 'cup', 122, 50, 12, 2, 0.5, ARRAY['Pantry|Canned foods', 'Pantry|Baking']),
    ('tomato-paste', 'Tomato paste', 'tomato paste', 'Tomato Product', 'tomato', ARRAY['canned tomato paste'], 2, 'tbsp', 33, 30, 7, 1.5, 0.2, ARRAY['Pantry|Canned foods', 'Condiments & Sauces|Sauces']),
    ('tomato-sauce', 'Tomato sauce', 'tomato sauce', 'Tomato Product', 'tomato', ARRAY['canned tomato sauce'], 0.5, 'cup', 123, 40, 9, 2, 0.3, ARRAY['Pantry|Canned foods', 'Condiments & Sauces|Sauces']),
    ('coconut-milk', 'Coconut milk', 'coconut milk', 'Canned Milk', 'coconut', ARRAY['canned coconut milk'], 0.25, 'cup', 60, 110, 2, 1, 11, ARRAY['Pantry|Canned foods', 'Pantry|Baking']),
    ('chicken-broth', 'Chicken broth', 'chicken broth', 'Broth', 'broth', ARRAY['chicken stock'], 1, 'cup', 240, 15, 1, 2, 0.5, ARRAY['Pantry|Canned foods']),
    ('cornstarch', 'Cornstarch', 'cornstarch', 'Baking Ingredient', 'baking', ARRAY['corn starch'], 1, 'tbsp', 8, 30, 7, 0, 0, ARRAY['Pantry|Baking']),
    ('baking-soda', 'Baking soda', 'baking soda', 'Baking Ingredient', 'baking', ARRAY['sodium bicarbonate'], 1, 'tsp', 4.6, 0, 0, 0, 0, ARRAY['Pantry|Baking']),
    ('cocoa-powder', 'Cocoa powder', 'cocoa powder', 'Baking Ingredient', 'chocolate', ARRAY['unsweetened cocoa'], 1, 'tbsp', 5, 12, 3, 1, 0.7, ARRAY['Pantry|Baking']),
    ('frozen-broccoli', 'Frozen broccoli', 'frozen broccoli', 'Frozen Vegetable', 'broccoli', ARRAY['broccoli frozen'], 1, 'cup', 91, 30, 5, 2.5, 0.3, ARRAY['Frozen|Frozen vegetables', 'Produce|Vegetables']),
    ('frozen-spinach', 'Frozen spinach', 'frozen spinach', 'Frozen Vegetable', 'spinach', ARRAY['spinach frozen'], 0.5, 'cup', 95, 30, 5, 3.5, 0.5, ARRAY['Frozen|Frozen vegetables', 'Produce|Vegetables']),
    ('frozen-peas', 'Frozen peas', 'frozen peas', 'Frozen Vegetable', 'peas', ARRAY['peas frozen'], 0.5, 'cup', 80, 67, 12, 4.3, 0.3, ARRAY['Frozen|Frozen vegetables']),
    ('frozen-corn', 'Frozen corn', 'frozen corn', 'Frozen Vegetable', 'corn', ARRAY['corn frozen'], 0.5, 'cup', 82, 72, 16, 2.5, 1, ARRAY['Frozen|Frozen vegetables']),
    ('frozen-mixed-vegetables', 'Frozen mixed vegetables', 'frozen mixed vegetables', 'Frozen Vegetable', 'vegetables', ARRAY['mixed vegetables frozen'], 0.75, 'cup', 95, 60, 12, 3, 0.5, ARRAY['Frozen|Frozen vegetables']),
    ('frozen-berries', 'Frozen berries', 'frozen berries', 'Frozen Fruit', 'berries', ARRAY['mixed berries frozen'], 1, 'cup', 140, 70, 17, 1, 0.5, ARRAY['Frozen|Frozen fruit', 'Produce|Fruit']),
    ('frozen-mango', 'Frozen mango', 'frozen mango', 'Frozen Fruit', 'mango', ARRAY['mango chunks frozen'], 1, 'cup', 140, 90, 22, 1, 0.5, ARRAY['Frozen|Frozen fruit']),
    ('frozen-shrimp', 'Frozen shrimp', 'frozen shrimp', 'Frozen Seafood', 'shrimp', ARRAY['shrimp frozen'], 3, 'oz', 85, 84, 0.2, 20, 0.3, ARRAY['Frozen|Frozen protein', 'Meat & Seafood|Seafood']),
    ('frozen-salmon-fillet', 'Frozen salmon fillet', 'frozen salmon fillet', 'Frozen Fish', 'salmon', ARRAY['salmon frozen'], 3, 'oz', 85, 177, 0, 17, 11, ARRAY['Frozen|Frozen protein', 'Meat & Seafood|Fish']),
    ('frozen-french-fries', 'Frozen french fries', 'frozen french fries', 'Frozen Potato', 'potato', ARRAY['frozen fries'], 3, 'oz', 85, 150, 23, 2, 5, ARRAY['Frozen|Frozen snacks']),
    ('walnuts', 'Walnuts', 'walnuts', 'Nuts', 'nuts', ARRAY['english walnuts'], 1, 'oz', 28, 185, 4, 4.3, 18.5, ARRAY['Snacks|Nuts & trail mix', 'Everyday|Quick snacks']),
    ('pistachios', 'Pistachios', 'pistachios', 'Nuts', 'nuts', ARRAY['shelled pistachios'], 1, 'oz', 28, 160, 8, 6, 13, ARRAY['Snacks|Nuts & trail mix', 'Everyday|Quick snacks']),
    ('pumpkin-seeds', 'Pumpkin seeds', 'pumpkin seeds', 'Seeds', 'seeds', ARRAY['pepitas'], 1, 'oz', 28, 160, 4, 8.5, 14, ARRAY['Snacks|Nuts & trail mix']),
    ('chia-seeds', 'Chia seeds', 'chia seeds', 'Seeds', 'seeds', ARRAY['dry chia seeds'], 1, 'tbsp', 12, 58, 5, 2, 3.7, ARRAY['Snacks|Nuts & trail mix', 'Everyday|Breakfast basics']),
    ('rice-cakes', 'Rice cakes', 'rice cakes', 'Cracker', 'cracker', ARRAY['plain rice cake'], 1, 'cake', 9, 35, 7.3, 0.7, 0.3, ARRAY['Snacks|Crackers', 'Everyday|Quick snacks']),
    ('pretzels', 'Pretzels', 'pretzels', 'Snack', 'pretzel', ARRAY['hard pretzels'], 1, 'oz', 28, 110, 23, 3, 1, ARRAY['Snacks|Crackers', 'Everyday|Quick snacks']),
    ('potato-chips', 'Potato chips', 'potato chips', 'Chips', 'chips', ARRAY['plain chips'], 1, 'oz', 28, 152, 15, 2, 10, ARRAY['Snacks|Chips']),
    ('granola-bar', 'Granola bar', 'granola bar', 'Bar', 'bar', ARRAY['oat bar'], 1, 'bar', 42, 180, 29, 4, 6, ARRAY['Snacks|Bars', 'Everyday|Quick snacks']),
    ('dark-chocolate', 'Dark chocolate', 'dark chocolate', 'Sweet Snack', 'chocolate', ARRAY['plain dark chocolate'], 1, 'oz', 28, 170, 13, 2, 12, ARRAY['Snacks|Sweet snacks']),
    ('coconut-water', 'Coconut water', 'coconut water', 'Drink', 'water', ARRAY['plain coconut water'], 1, 'cup', 240, 46, 9, 1.7, 0.5, ARRAY['Drinks|Water']),
    ('unsweetened-almond-milk', 'Unsweetened almond milk', 'unsweetened almond milk', 'Milk Alternative', 'milk', ARRAY['almond beverage'], 1, 'cup', 240, 30, 1, 1, 2.5, ARRAY['Drinks|Protein drinks', 'Dairy & Eggs|Milk']),
    ('soy-milk', 'Soy milk', 'soy milk', 'Milk Alternative', 'milk', ARRAY['soy beverage'], 1, 'cup', 243, 100, 8, 7, 4, ARRAY['Drinks|Protein drinks', 'Dairy & Eggs|Milk']),
    ('oat-milk', 'Oat milk', 'oat milk', 'Milk Alternative', 'milk', ARRAY['oat beverage'], 1, 'cup', 240, 120, 16, 3, 5, ARRAY['Drinks|Protein drinks', 'Dairy & Eggs|Milk']),
    ('kombucha', 'Kombucha', 'kombucha', 'Tea', 'tea', ARRAY['fermented tea'], 1, 'cup', 240, 35, 8, 0, 0, ARRAY['Drinks|Coffee / tea']),
    ('green-tea', 'Green tea', 'green tea', 'Tea', 'tea', ARRAY['brewed green tea'], 1, 'cup', 237, 2, 0, 0, 0, ARRAY['Drinks|Coffee / tea']),
    ('diet-soda', 'Diet soda', 'diet soda', 'Soda', 'soda', ARRAY['diet cola'], 1, 'can', 355, 0, 0, 0, 0, ARRAY['Drinks|Soda']),
    ('apple-cider-vinegar', 'Apple cider vinegar', 'apple cider vinegar', 'Vinegar', 'vinegar', ARRAY['cider vinegar'], 1, 'tbsp', 15, 3, 0.1, 0, 0, ARRAY['Condiments & Sauces|Sauces']),
    ('balsamic-vinegar', 'Balsamic vinegar', 'balsamic vinegar', 'Vinegar', 'vinegar', ARRAY['balsamic'], 1, 'tbsp', 16, 14, 2.7, 0, 0, ARRAY['Condiments & Sauces|Sauces', 'Condiments & Sauces|Dressings']),
    ('rice-vinegar', 'Rice vinegar', 'rice vinegar', 'Vinegar', 'vinegar', ARRAY['rice wine vinegar'], 1, 'tbsp', 15, 0, 0, 0, 0, ARRAY['Condiments & Sauces|Sauces']),
    ('worcestershire-sauce', 'Worcestershire sauce', 'worcestershire sauce', 'Sauce', 'sauce', ARRAY['worcestershire'], 1, 'tbsp', 17, 13, 3.3, 0, 0, ARRAY['Condiments & Sauces|Sauces']),
    ('fish-sauce', 'Fish sauce', 'fish sauce', 'Sauce', 'fish sauce', ARRAY['nam pla'], 1, 'tbsp', 18, 6, 0.7, 0.9, 0, ARRAY['Condiments & Sauces|Sauces']),
    ('oyster-sauce', 'Oyster sauce', 'oyster sauce', 'Sauce', 'sauce', ARRAY['oyster flavored sauce'], 1, 'tbsp', 18, 15, 3, 0.5, 0, ARRAY['Condiments & Sauces|Sauces']),
    ('sriracha', 'Sriracha', 'sriracha', 'Hot Sauce', 'pepper', ARRAY['chili garlic sauce'], 1, 'tsp', 5, 5, 1, 0, 0, ARRAY['Condiments & Sauces|Sauces']),
    ('chili-powder', 'Chili powder', 'chili powder', 'Seasoning', 'spice', ARRAY['ground chili seasoning'], 1, 'tsp', 3, 8, 1.4, 0.4, 0.4, ARRAY['Condiments & Sauces|Seasonings']),
    ('ground-cumin', 'Ground cumin', 'ground cumin', 'Seasoning', 'spice', ARRAY['cumin powder'], 1, 'tsp', 2, 8, 0.9, 0.4, 0.5, ARRAY['Condiments & Sauces|Seasonings']),
    ('black-pepper', 'Black pepper', 'black pepper', 'Seasoning', 'spice', ARRAY['ground black pepper'], 1, 'tsp', 2, 5, 1.3, 0.2, 0.1, ARRAY['Condiments & Sauces|Seasonings']),
    ('vegetable-soup', 'Vegetable soup', 'vegetable soup', 'Soup', 'soup', ARRAY['mixed vegetable soup'], 1, 'cup', 245, 90, 16, 3, 2, ARRAY['Prepared|Ready meals']),
    ('lentil-soup', 'Lentil soup', 'lentil soup', 'Soup', 'soup', ARRAY['prepared lentil soup'], 1, 'cup', 250, 180, 30, 12, 3, ARRAY['Prepared|Ready meals']),
    ('mashed-potatoes', 'Mashed potatoes', 'mashed potatoes', 'Prepared Potato', 'potato', ARRAY['plain mashed potatoes'], 1, 'cup', 210, 237, 35, 4, 8.9, ARRAY['Prepared|Ready meals']),
    ('grilled-chicken-salad', 'Grilled chicken salad', 'grilled chicken salad', 'Salad', 'chicken', ARRAY['chicken garden salad'], 1, 'bowl', 300, 320, 14, 34, 15, ARRAY['Prepared|Ready meals']),
    ('fried-rice', 'Fried rice', 'fried rice', 'Rice Meal', 'rice', ARRAY['vegetable fried rice'], 1, 'cup', 198, 333, 42, 8, 13, ARRAY['Prepared|Restaurant / fast food'])
),
seed_rows AS (
  SELECT
    seed_foods.*,
    ('catalog:expanded:' || canonical_key || ':' || serving_grams::text) AS dedupe_key,
    jsonb_build_object(
      'canonical_key', canonical_key,
      'foodKey', canonical_key,
      'food_family', food_family,
      'canonical_food_name', name,
      'icon', jsonb_build_object('name', icon_name),
      'search_aliases', to_jsonb(search_aliases),
      'category', browse_placements[1],
      'browse',
      (
        SELECT jsonb_agg(
          jsonb_build_object(
            'department', split_part(placement.value, '|', 1),
            'aisle', split_part(placement.value, '|', 2)
          )
          ORDER BY placement.ordinality
        )
        FROM unnest(seed_foods.browse_placements) WITH ORDINALITY AS placement(value, ordinality)
      ),
      'seed_version', 'expanded_food_catalog_v1',
      'data_quality', 'generic_estimate',
      'nutrition_basis', 'per_serving',
      'nutrition_per_serving', jsonb_build_object(
        'calories', calories,
        'carbs_g', carbs_g,
        'protein_g', protein_g,
        'fat_g', fat_g
      )
    ) AS seed_metadata
  FROM seed_foods
)
INSERT INTO public.foods (
  name,
  normalized_name,
  brand_name,
  normalized_brand_name,
  serving_size,
  serving_unit,
  serving_grams,
  calories,
  carbs_g,
  protein_g,
  fat_g,
  source,
  dedupe_key,
  created_by_user_id,
  is_active,
  metadata
)
SELECT
  name,
  normalized_name,
  NULL,
  NULL,
  serving_size,
  serving_unit,
  serving_grams,
  calories,
  carbs_g,
  protein_g,
  fat_g,
  'catalog',
  dedupe_key,
  NULL,
  true,
  seed_metadata
FROM seed_rows
WHERE NOT EXISTS (
  SELECT 1
  FROM public.foods AS existing
  WHERE existing.dedupe_key = seed_rows.dedupe_key
    OR (
      existing.created_by_user_id IS NULL
      AND existing.normalized_name = seed_rows.normalized_name
      AND existing.normalized_brand_name IS NULL
    )
);

COMMIT;
